name: Daily Run

on:
  schedule:
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Run the script
      run: python main.py
      env:
        TOKEN: ${{ secrets.DISCORD_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
